name: tests

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          package-manager-cache: false

      - name: Install pnpm
        run: npm install -g pnpm@^10

      - name: Install npm deps
        run: pnpm install --frozen-lockfile

      - name: Build action
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Execute this action
        uses: ./
        with:
          ec2_instance_id: ${{ vars.EC2_INSTANCE_ID }}
          run_as_user: ubuntu
          log_bucket_name: ${{ secrets.LOG_BUCKET_NAME }}
          commands: |
            set -e
            pwd
            cd /home/ubuntu
            ls -al
            sleep 4s
            echo -e '\033[32mColorful text\033[0m'
            echo "Hello from EC2"

